### PR TITLE
Adds buttons to test availability of server from public internet

### PR DESCRIPTION
**Pull request by chaptergy**
Adds buttons to test whether the domains are available to the public internet for certs. Pressing the button places a dummy file in the `.well-known` directory where the challenge would be, and checks whether the file is requestable using [site24x7.com](https://www.site24x7.com/tools/restapi-tester.html).

image
image
image
image

### CODE REVIEW

**Comment by jc21** [comment]
This is an automated message from CI:

Docker Image for build 2 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-1538`

**Note:** ensure you backup your NPM instance before testing this PR image! Especially if this PR contains database changes.

**Comment by jc21** [comment]
This is an automated message from CI:

Docker Image for build 3 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-1538`

**Note:** ensure you backup your NPM instance before testing this PR image! Especially if this PR contains database changes.

**Comment by jc21** [comment]
Awesome improvement. I just pulled the image to test and wondering what you expect to happen for a domain that is pointing to NPM already but doesn't have a proxy host yet? For me it errors but I'd expect it to still work I think.

**Comment by chaptergy** [comment]
In https://github.com/jc21/nginx-proxy-manager/commit/d34691152ca5efd93087a343d423fadcd6e06989 I added the letsencrypt challenge config to the default host config, so it should work even for domains which do not have a host yet. So for you this causes an error but it works when you have created a host?

**Comment by jc21** [comment]
Screen Shot 2021-11-03 at 10 24 34 am

Screen Shot 2021-11-03 at 10 25 05 am

**Comment by jc21** [comment]
I'm seeing this in the container startup, not sure if it's related:

Screen Shot 2021-11-03 at 10 31 39 am

**Comment by chaptergy** [comment]
Hm, that's weird, I'm pretty sure I tested it on an instance which did not have any proxy hosts at all. But I'll try to replicate the problem later and fix it.

**Comment by chaptergy** [comment]
I can't replicate your issue, I have set up a server with no proxy hosts at all, and it works as expected. Are you sure you haven't set up your DNS to redirect somewhere else? 

When visiting the url which returns the error for you it does not seem like npm is running there. Because on an npm instance requesting `<domain>/.well-known/acme-challenge/test` should return the default openresty 404 page, and should not show the default host. It seems this is not the case for your tested domain.

**Comment by chaptergy** [comment]
I can't replicate your issue, I have set up a server with no proxy hosts at all, and it works as expected. Are you sure you haven't set up your DNS to redirect somewhere else? 

When visiting the url which returns the error for you it does not seem like npm is running there. Because on an npm instance requesting `<domain>/.well-known/acme-challenge/test` should return the default openresty 404 page, and should not show the default host. It seems this is not the case for your tested domain.

**Comment by jc21** [comment]
This is an automated message from CI:

Docker Image for build 4 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-1538`

**Note:** ensure you backup your NPM instance before testing this PR image! Especially if this PR contains database changes.

**Comment by jc21** [comment]
I've recorded a video: http://public.jc21.com/nginx-proxy-manager/temp/npm-host-check.mov

I have a wildcard dns for `*.jc21.com` that points to my npm instance.

1. Tested `test.jc21.com` connectivity without any existing host for it, expected PASS got FAIL. Logs:
```
ℹ  info      HTTP challenge test failed for domain test.jc21.com because of invalid returned data: <html>
<head>
  <title>404, page not found.</title>
  <style>
...
```
which is my custom 404 page, see http://test.jc21.com

2. Created a proxy host that points to npm to see if that fixes it, expected PASS got FAIL. Logs:
```
ℹ  info      HTTP challenge test failed for domain test.jc21.com because of invalid returned data: <!doctype html><html lang="en" dir="ltr">
...
```
which is the NPM index page

3. Applied an existing SSL cert to that host, expected PASS got PASS.

My first thought was that you're sending HTTPS for the url, but you're not so that can't be it.

**Comment by jc21** [comment]
This is an automated message from CI:

Docker Image for build 5 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-1538`

**Note:** ensure you backup your NPM instance before testing this PR image! Especially if this PR contains database changes.

**Comment by chaptergy** [comment]
Ahhhh, the problem is I only recently added the letsencrypt acme challenge to the default host template. So if the default host type hasn't been changed recently, it does not contain the acme challenge. It's not really the use case for a migration but I think adding a migration which just regenerates the default host config would be the best solution.

**Comment by jc21** [comment]
This is an automated message from CI:

Docker Image for build 9 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-1538`

**Note:** ensure you backup your NPM instance before testing this PR image! Especially if this PR contains database changes.

**Comment by jc21** [comment]
Working :)

**Pull request merged**
