### PR TITLE
Fixes custom certificate upload modal

### PR DESCRIPTION
**Pull request by chaptergy**
Fixes https://github.com/jc21/nginx-proxy-manager/issues/1676

### CODE REVIEW

**Comment by jc21** [comment]
This is an automated message from CI:

Docker Image for build 1 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-1677`

**Note:** ensure you backup your NPM instance before testing this PR image! Especially if this PR contains database changes.

**Comment by SolarisEclipse** [comment]
# Modal is still broken. 

I can see that this commit is having issues, but it doesn't seem to have fixed the modal. I pulled and launched GitHub-pr-1677, but the modal is still broken. 

ezgif-3-fe0b2f44ff

Screen Shot 2021-12-23 at 9 12 31 AM

**Comment by chaptergy** [comment]
@SolarisEclipse Have you cleared your browser cache so you are sure you are not seeing the cached old version of the website?

**Comment by SolarisEclipse** [comment]
Verifying, I hope I wasn't stupid enough to forget that. haha

**Comment by SolarisEclipse** [comment]
Nope, still broken. I didn't think I'd forget something like that. here's a gif.
ezgif-5-7b3cb77fdc

**Comment by hyun007** [comment]
the fix works for me

**Comment by SolarisEclipse** [comment]
> the fix works for me

That's great! I ended up moving on and just ended up learning nginx myself. I don't need a monkey brain mode of nginx. It's just a nice to have. I've since deleted nginx proxy manager and just started using nginx vanilla.

**Comment by krause3284** [comment]
Fix doesnt work for me

**Comment by jonyhartron** [comment]
Fix worked for me. thanks @chaptergy

**Comment by DrProphet0** [comment]
After updating and clearing the cache it fixed the issue.
Thank you!

**Comment by chaptergy** [comment]
For anyone where this fix doesn't seem to work, make sure you have cleared the browser cache. If the issue still persists, I'll need to know the logs of your [browsers developer console](https://balsamiq.com/support/faqs/browserconsole/) to know what the issue might be

**Comment by mikedelgaudio** [comment]
This fix worked for me!

**Comment by hoochster** [comment]
This did work for me as well.  Thank you so much.  So when time comes to upgrade, just changing back to latest should work fine?

**Comment by chaptergy** [comment]
@hoochster Yes, once 2.9.14 is released, you can just swich your tag back to that

**Comment by wrightmt** [comment]
Great this worked, thanks!

**Pull request merged**
