### PR TITLE
Add deSEC DNS provider

### PR DESCRIPTION
**Pull request by FMeinicke**

### CODE REVIEW

**Comment by jc21** [comment]
This is an automated message from CI:

Docker Image for build 1 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-1300`

**Note:** ensure you backup your NPM instance before testing this PR image! Especially if this PR contains database changes.

**Comment by jc21** [comment]
This is an automated message from CI:

Docker Image for build 2 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-1300`

**Note:** ensure you backup your NPM instance before testing this PR image! Especially if this PR contains database changes.

**Comment by jc21** [comment]
As this is a new provider I leave it up to you to test this with the docker image above and let us know things work as expected.

**Comment by FMeinicke** [comment]
I pulled the image and tested it locally and it works fine for me.

**Comment by SpaceAgeHero** [comment]
Please update, because DNS challenge is broken with CNAME / delegated domains.
https://github.com/desec-io/certbot-dns-desec/releases/tag/v1.3.2

**Pull request merged**
