### PR TITLE
Check also certificate keys using elliptic curve algorithms

### PR DESCRIPTION
**Pull request by mkochenough**
This should help with issue #663.

### CODE REVIEW

**Comment by jc21** [comment]
Docker Image for build 2 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-665`

**Comment by mkochenough** [comment]
Thanks for this hint. I used this docker image. It still fails to import the key. Unfortunately the error message is empty. I will dig a bit around to fix this.

**Comment by MarceloLagos** [comment]
The error message is empty because it doesn't fail the openssl command. Instead it works, but the output is empty, therefore it fails the check to see if "key ok" is in there.
Furthermore even if that doesn't fail, the check will since the verification for EC keys doesn't return "key ok" anywhere. See my post on #663

**Comment by jc21** [comment]
Docker Image for build 3 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-665`

**Pull request closed without merging**
