### PR TITLE
v2.7.2

### PR DESCRIPTION
**Pull request by jc21**

### CODE REVIEW

**Comment by jc21** [comment]
Docker Image for build 1 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-806`

**Comment by Sabrimjd** [comment]
Hello, from 2.7.1 i got an error log : 

[1/6/2021] [1:53:46 PM] [Migrate  ] › ℹ  info      Current database version: 20201014143841


[1/6/2021] [1:53:46 PM] [Global   ] › ✖  error     The migration directory is corrupt, the following files are missing: 20200522113248_openid_connect.js, 20200522144240_openid_allowed_users.js

have a nice day, and thanks for this awesome app

**Comment by jc21** [comment]
> 20200522144240_openid_allowed_users

This is because you have used a docker image from the OIDC branch or PR. There is a migration file in there that has been run on your database. As a result, you have to revert these database changes in order to use the main branch. This is the risk with using code that is not merged yet.

[This is the migration](https://github.com/jc21/nginx-proxy-manager/blob/openidc/backend/migrations/20200522144240_openid_allowed_users.js) you'll need to revert. Connect to your database:
```sql
ALTER TABLE proxy_host DROP COLUMN openidc_restrict_users_enabled;
ALTER TABLE proxy_host DROP COLUMN openidc_allowed_users;
DELETE FROM migrations WHERE name="20200522144240_openid_allowed_users.js";
```

**Comment by jc21** [comment]
I also forgot that [this migration](https://github.com/jc21/nginx-proxy-manager/blob/openidc/backend/migrations/20200522113248_openid_connect.js) will also need reverting:

```sql
ALTER TABLE proxy_host DROP COLUMN openidc_enabled;
ALTER TABLE proxy_host DROP COLUMN openidc_redirect_uri;
ALTER TABLE proxy_host DROP COLUMN openidc_discovery;
ALTER TABLE proxy_host DROP COLUMN openidc_auth_method;
ALTER TABLE proxy_host DROP COLUMN openidc_client_id;
ALTER TABLE proxy_host DROP COLUMN openidc_client_secret;
DELETE FROM migrations WHERE name="20200522113248_openid_connect.js";
```

**Pull request merged**
