### PR TITLE
Allow DNS challenges not just for cloudflare

### PR DESCRIPTION
**Pull request by chaptergy**
This merge request would allow way more providers for DNS challenges to request wildcard certificates, not just for Cloudflare users.  
These new providers are collected in an easily maintainable list `global/certbot-dns-plugins.js`.

As a little bonus "Internal Errors" as thrown by the backend now show the stack of what exactly went wrong, so users can sort out some problems on their own. This was requested in issue https://github.com/jc21/nginx-proxy-manager/issues/627 as well.

### CODE REVIEW

**Comment by jc21** [comment]
Docker Image for build 6 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-635`

**Comment by jc21** [comment]
Docker Image for build 7 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-635`

**Comment by jc21** [comment]
Amazing work! I'm unable to test 100% because I use AWS Route53 for my DNS and it's not in the list. Can you confirm which providers you have successfully tested with?

**Comment by jc21** [comment]
Docker Image for build 8 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-635`

**Comment by chaptergy** [comment]
Route 53 is at the very bottom of the list but should be there.
Unfortunately I myself was only able to test Njalla, and get a friend of mine to test DNSimple, however I figured no one would be able to test all of them, and if issues were present, they would arise over time. Issues would not be able to break any other working code and the list of providers would be easily maintainable. So removing a broken provider or changing it when the certbot plugin changes would require minimal effort and could be done by almost anyone.

**Comment by jc21** [comment]
Ah yep I didn't look hard enough.

So I just tried this out and got this:

```
[10/14/2020] [5:30:02 AM] [Express  ] › ⚠  warning   Command failed: /usr/bin/certbot certonly --non-interactive --cert-name "npm-76" --agree-tos --email "jc@jc21.com" --domains "dnstest.jc21.net.au" --authenticator dns-route53 --dns-route53-credentials "/etc/letsencrypt/credentials-76"
usage:
  certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...

Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the
certificate.
certbot: error: unrecognized arguments: --dns-route53-credentials /etc/letsencrypt/credentials-76
```

Looks like the arg isn't supported, and not sure if it's required since the AWS creds have to be supplied in other ways [according to the certbot docs](https://certbot-dns-route53.readthedocs.io/en/stable/).

**Comment by chaptergy** [comment]
Oh yeah, AWS was the odd one out, I had a special case just for AWS in the frontend, however when it came to the backend I totally forgot about it. Unfortunately I can't test it myself, however I pushed some changes which I'm pretty sure should get Route53 working.

**Comment by jc21** [comment]
Docker Image for build 10 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-635`

**Comment by jc21** [comment]
Route53 works now :)

**Comment by aroundmyroom** [comment]
how can I update for this?

**Comment by jc21** [comment]
Yep that will work once this is part of the main release. I usually create an official release a couple of days after going on a PR merge spree.

You can watch releases for this with the Watch button at that top of this page and when you get the email, do your update.

**Pull request merged**
