### PR TITLE
v2.9.7

### PR DESCRIPTION
**Pull request by jc21**

### CODE REVIEW

**Comment by jc21** [comment]
This is an automated message from CI:

Docker Image for build 1 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-1294`

**Note:** ensure you backup your NPM instance before testing this PR image! Especially if this PR contains database changes.

**Comment by jc21** [comment]
This is an automated message from CI:

Docker Image for build 2 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-1294`

**Note:** ensure you backup your NPM instance before testing this PR image! Especially if this PR contains database changes.

**Comment by natanparmigianoreis** [comment]
Hello Everyone!
First of all, i love the work you guys have done here! Thats a great tool for managing ingress meshs on docker swarm environments.

In the latest release (2.9.7) i suspect that a new bug has been introduced by commit [6c1ae77](https://github.com/jc21/nginx-proxy-manager/commit/6c1ae77a2a40283c5444c2f7e0a7c8227aeecbd2).

I found that using multiple locations nginx gets "confused" on the scope of the $upstream variable and sends requests to the wrong endpoint, causing redirection errors or worse on complex configurations.

For now reverting to 2.9.6 solved the issue, but i found it important to make the mantainers aware of the issue

**Comment by jc21** [comment]
Thanks @natanparmigianoreis

Are you able to provide some replication steps and example of the problem?

**Pull request merged**
