### PR TITLE
Selection of the ssl protocols/ciphers is done using the default sever block

### PR DESCRIPTION
**Pull request by jlesage**
The check for allowed SSL protocols is done before SNI, thus the default server block is always used.

See https://www.ruby-forum.com/t/ssl-protocols-per-server/232557/11

### CODE REVIEW

**Comment by jc21** [comment]
Docker Image for build 1 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-189-amd64`

**Comment by jc21** [comment]
Yeah this aNull thing was a suggestion by someone previously so that anyone wanting SSL on a unconfigured hostname would "fail fast", but I don't really think it was a big deal either way.

Can you please change this PR to the `develop` branch?

**Comment by jlesage** [comment]
Yes it was me that initially proposed the aNull change... but it seems that I didn't realized the side effect this was causing.

I changed to PR to `develop` branch.

**Comment by jc21** [comment]
Docker Image for build 2 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-189-amd64`

**Comment by jc21** [comment]
Docker Image for build 3 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-189-amd64`

**Comment by jc21** [comment]
Will create a new versioned release soon, just waiting to hear about another pr

**Pull request merged**
