### PR TITLE
Improve terminal script colors

### PR DESCRIPTION
**Pull request by Indemnity83**
If a terminal cannot interpret \e[* color codes, then it will be "polluted" which makes output harder to read. tput will handle escape characters depending on the terminal capabilities.

Screen Shot 2020-04-15 at 10 04 19 PM
Screen Shot 2020-04-15 at 10 03 51 PM

### CODE REVIEW

**Comment by jc21** [comment]
Yeah I used to use tput but not all docker containers had it installed for my scripts. In this case, for this project, we can go with it.

**Comment by Indemnity83** [comment]
Let me fix my git history not sure what happened there. 

Also looks like as you mentioned the docker containers don't have tput

**Comment by jc21** [comment]
The build is failing because TERM env var is not set in the docker build. Just add
```
ENV TERM=xterm-256color
```
to line 17 of the [Dockerfile](https://github.com/Indemnity83/nginx-proxy-manager/blob/script-colors/docker/Dockerfile) and the build should be ok

**Comment by jc21** [comment]
This is failing CI because of unrelated reasons I introduced recently. A rebase will fix it after I fix the branch

**Comment by Indemnity83** [comment]
I probably should have just squashed the commits at this point, but I'll just let the build finish to make sure it's working properly and you can decide to squash and merge or just merge.

**Comment by jc21** [comment]
You'll have to merge `jc21:develop` to your branch and push again for the build to work I think

**Comment by Indemnity83** [comment]
went a different route; extracted a log helper to make changes more universal but I also found that using `printf` instead of `echo -e` seems to work in more places and shouldn't have the problem that tput had with dockers lack of a terminal.

**Comment by jc21** [comment]
Closing due to inactivity

**Pull request closed without merging**
