### PR TITLE
Forward scheme and http code added for redirection hosts

### PR DESCRIPTION
**Pull request by baruffaldi**
You can now configure the forward_scheme and forward_http_code on user interface (section redirection hosts)

### CODE REVIEW

**Comment by jc21** [comment]
Docker Image for build 3 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-883`

**Comment by jc21** [comment]
Docker Image for build 4 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-883`

**Comment by jc21** [comment]
Docker Image for build 5 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-883`

**Comment by jc21** [comment]
Docker Image for build 10 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-883`

**Comment by jc21** [comment]
Docker Image for build 11 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-883`

**Review by delangen-jas — CHANGES_REQUESTED** [review]
Thank you

**Comment by jc21** [comment]
Docker Image for build 12 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-883`

**Comment by jc21** [comment]
Docker Image for build 13 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-883`

**Comment by jc21** [comment]
Great work :)

**Comment by baruffaldi** [comment]
> Great work :)

Thank you @jc21 really :)

**Pull request merged**
