### PR TITLE
Fix wrap for tags

### PR DESCRIPTION
**Pull request by Steven-Harris**
Added some flex layout for styling. I was not sure where you would like the styling. Let me know if you want it moved

Fixes [#56]

### CODE REVIEW

**Comment by jc21** [comment]
Docker Image for build 1 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-195-amd64`

**Comment by jc21** [comment]
Could you please change this to the `develop` branch so we can keep the versions separated :)

**Comment by Steven-Harris** [comment]
sure thing!

**Comment by jc21** [comment]
Docker Image for build 2 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-195-amd64`

**Comment by jc21** [comment]
Docker Image for build 3 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-195-amd64`

**Pull request merged**
