### PR TITLE
Added TransIP dns provider

### PR DESCRIPTION
**Pull request by nielscil**
Added TransIP dns provider

### CODE REVIEW

**Comment by jc21** [comment]
Docker Image for build 2 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-942`

**Comment by jc21** [comment]
Docker Image for build 3 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-942`

**Comment by jc21** [comment]
ugh this conflicted with something I merged and I used github to resolve it, but I missed a closing brace and I can't edit it again. Could you please pull the latest changes from this `develop` branch and push your changes up again?

**Comment by jc21** [comment]
Docker Image for build 6 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-942`

**Comment by nielscil** [comment]
> ugh this conflicted with something I merged and I used github to resolve it, but I missed a closing brace and I can't edit it again. Could you please pull the latest changes from this `develop` branch and push your changes up again?

Fixed the errors

**Comment by jc21** [comment]
Cheers

**Pull request merged**
