### PR TITLE
Fixes custom certificate upload

### PR DESCRIPTION
**Pull request by chaptergy**
Unfortunately the custom certificate upload was broken since the introduction of the Cloudflare DNS challenge. See https://github.com/jc21/nginx-proxy-manager/issues/594. This pull request fixes those issues.

### CODE REVIEW

**Comment by jc21** [comment]
Docker Image for build 1 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-656`

**Comment by jc21** [comment]
Nice work thanks again :)

**Comment by kuznetz** [comment]
thanks!

**Comment by mcnahum** [comment]
If I can now properly upload the certificate I cannot assign it to my Proxy host... only me?

**Comment by chaptergy** [comment]
@mcnahum Unfortunately I'm not able to reproduce your problem. I am able to successfully upload a custom certificate and set it as a certificate in a proxy host.
If your problem persists please open a new issue with some more details. 
Thanks!

**Comment by Maxiggapp** [comment]
Hello guys! 
I had the same problem, using my GeoTrust-Certificate, 
**BUT I FOUND A SOLUTION:**
1. Open the nginx-proxy-manager in your browser.
2. Create a LetsEncrypt-Certificate for your Domain (mydomain.com + www.mydomain.com)
3. Now go to that config-file via terminal or via ftp: /root/npm/data/nginx/proxy_host (eg.: 3.conf / see file-create-timestamp)
4. Open that conf-file in your VS-Code or terminal with vim/nano
5. Find this line: include conf.d/include/letsencrypt-acme-challenge.conf; AND COMMENT IT OUT --- save the file
6. Now go to your new LetsEncrypt-Certificate-Files: /root/npm/letsencrypt/archive/npm-3 (see file-create-timestamp)
7. Open the file "fullchain1.pem", delete all inside and put all of your OWN cer-file inside (eg. your file named mydomain.cer)
8. Open the file "privkey1.pem", delete all inside and put all of your OWN key-file inside (eg. your file named mydomain.key)
9. Save these two files and in /root/npm run "docker-compose up -d" again
10. In my case, i did a server-reboot too.
11. THAT'S IT !
12. You can check your Certificate in the Browser by clicking the Lock-Icon or you can check the Certificate in the nginx-proxy-server in the browser by editing your Proxy-Host (your Domain) and go to SSL-Tab. Click in the window where your domain-name is written (mydomain.com, www.mydomain.com) and you will see, that your expiring-date of this "LetsEncrypt"-Certificate is the expiration-date of your real own buyed Certificate.

This is a simple trick, and i hope i could help you all.
I like the NginxProxyManager, because the handling is so easy.
Wish you all a happy coding year 2021,
Guido

**Pull request merged**
