### PR TITLE
Add DNS CloudFlare with wildcard support

### PR DESCRIPTION
**Pull request by jipjan**
Adds the option to use CloudFlare DNS (with wildcards) while requesting a Let's Encrypt certificate.
The options to revoke and renew have also been added.

It might be useful later to support more certbot plugins, but for now this is the one I required.

### CODE REVIEW

**Comment by jc21** [comment]
Docker Image for build 2 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-572`

**Comment by jc21** [comment]
Thanks for doing all the hard work!

Can I ask that multiple people are able to test this feature and report success as I don't use Cloudfare myself.

**Comment by jc21** [comment]
Docker Image for build 3 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-572`

**Comment by mosi1276** [comment]
What a great day to stop by and see what's been going on with the project. 

First, let me just say to @jc21 that I have tested the build 3 and I was able to pull Wildcard DNS Cloudflare certs for 6 of my domains without a problem. Now I just need to fully grasp how this will benefits me within NgnixProxyManager. I'm confident it will, my brain isn't on the dev cycle like some of my mates here.

In the expectation that I will figure out how this will improve my normal routine of keyboard smashing and hair pulling, a BIG thanks to @jipjan for putting in the pull request and the legwork and again to @jc21 for implementing it so quickly.

Cheers!

**Comment by ugoviti** [comment]
Thank you very much for that PR! It's very useful and works like a charm. Big thanks @jipjan and @jc21 for making NPM!

**Comment by cristiangauma** [comment]
Awesome job!. Is there an easy way to support OVH dns too?

**Comment by Freshhat** [comment]
Great job!

Can we please also add the support for netcup DNS certbot plugin? https://pypi.org/project/certbot-dns-netcup/

**Comment by toby-griffiths** [comment]
Awesome.  I was just trying this add on this week & wished it did this.  Thank you 🙏

**Pull request merged**
