### PR TITLE
Pass/Don't Pass Auth Header

### PR DESCRIPTION
**Pull request by jmwebslave**
Allows auth information from AccessList not to be passed to proxied hosts.  Resolves issue #153.

### CODE REVIEW

**Comment by jmwebslave** [comment]
Apologies if I haven't made this pull request correctly - it's actually my first time contributing to a project, so happy to take your guidance/feedback if I have messed up.

As far as the code itself is concerned, it's pretty straightforward I think.

The purpose of this one is so that proxied hosts aren't passed the authentication headers from nginx - in a large part to fix software packages that support basic auth among their auth set.  phpipam is one such example, and the use case here is that I have it set up for radius authentication, however if it gets basic auth it won't show a login page and will instead use the credentials in the header to query against radius.

**Comment by jc21** [comment]
Docker Image for build 1 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-653`

**Comment by jc21** [comment]
Looks good, can I just get you to rebase this PR on the develop branch, seems there might be a small conflict. Cheers

**Comment by jmwebslave** [comment]
Sorry about that, won't make that mistake again :).  Rebase isn't something I've had to do a lot of but I think I've managed to get it rebased on develop.  Appreciate your patience with me.

**Comment by jc21** [comment]
There are linting errors but I'll merge anyway and fix later

**Comment by jmwebslave** [comment]
Sorry about that.  I'll keep an eye on develop to see what changed.  I doubt I have my IDE set up for proper linting for this project as it took me a while to feel my way through being able to build it locally.  Thanks for such a great project - looking under the hood it's really well made.

**Comment by jc21** [comment]
Looks like it was in a file you didn't touch so not sure what happened.. all good

**Pull request merged**
