### PR TITLE
Removes the need of a config file and allows db config via environment

### PR DESCRIPTION
**Pull request by chaptergy**
This PR will remove the need of a config file and will generate one at boot from environment variables. This will make setup even easier and will allow easy setup though Docker GUIs like Portainer.

### CODE REVIEW

**Comment by jc21** [comment]
Docker Image for build 2 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-704`

**Comment by chaptergy** [comment]
I was not able to find any issues using this build.

**Comment by jc21** [comment]
Docker Image for build 3 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-704`

**Comment by jc21** [comment]
Sorry for the delay. Awesome stuff. I had a concern about people who were to update their docker image to this one without migrating configuration, but you seemed to have that covered :)

**Pull request merged**
