### PR TITLE
Adds logrotation

### PR DESCRIPTION
**Pull request by chaptergy**
This PR adds logrotation to the access and error logs of the hosts. both are rotated weekly. For access logs the last 4 files (=4 weeks) are kept, for error logs the last 10 files are kept.

Running performing the dry-run with
```
logrotate -d /etc/logrotate.d/nginx-proxy-manager
```

seems to work as expected, however we will have to wait to see if it actually does everything as expected.

Fixes https://github.com/jc21/nginx-proxy-manager/issues/183.

### CODE REVIEW

**Comment by chaptergy** [comment]
Hm, when running the buildx script locally on the current dev branch it runs into the same error as the pipeline, so i think this has nothing to do with my changes, though it does seem suspicios as the line with my changes seems to cause the error

**Comment by jc21** [comment]
This is an automated message from CI:

Docker Image for build 3 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-1140`

**Note:** ensure you backup your NPM instance before testing this PR image! Especially if this PR contains database changes.

**Comment by jc21** [comment]
This is an automated message from CI:

Docker Image for build 4 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-1140`

**Note:** ensure you backup your NPM instance before testing this PR image! Especially if this PR contains database changes.

**Comment by jc21** [comment]
So when/how does the logrotate binary run?

**Comment by chaptergy** [comment]
Logrotate should automatically add itself as a daily cronjob but only rotate the logs weekly as per the config.

**Comment by jc21** [comment]
So the problem with that is that there is no cron daemon running in the container so nothing will happen.

You can either add crond and start it in the same way as the nginx service or have the nodejs backend run the log rotate binary in a similar way to how it runs certbot periodically.

**Comment by chaptergy** [comment]
Ah, I assumed certbot was running via cron as well, not manually, but makes sense.

**Comment by jc21** [comment]
This is an automated message from CI:

Docker Image for build 6 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-1140`

**Note:** ensure you backup your NPM instance before testing this PR image! Especially if this PR contains database changes.

**Comment by jc21** [comment]
This is an automated message from CI:

Docker Image for build 7 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-1140`

**Note:** ensure you backup your NPM instance before testing this PR image! Especially if this PR contains database changes.

**Comment by chaptergy** [comment]
I finally got around to changing it. I'm now running it on my production server for a while, to verify it working.

**Comment by jc21** [comment]
This is an automated message from CI:

Docker Image for build 8 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-1140`

**Note:** ensure you backup your NPM instance before testing this PR image! Especially if this PR contains database changes.

**Comment by chaptergy** [comment]
I have now hat it running on my personal production server for a while, and I think it is ready to be merged. @jc21

**Pull request merged**
