### PR TITLE
Fixes dnspod credentials template

### PR DESCRIPTION
**Pull request by chaptergy**
Fixes https://github.com/jc21/nginx-proxy-manager/issues/1599

### CODE REVIEW

**Comment by chaptergy** [comment]
CI fails due to node-gyp not being able to download a tarball, so it has nothing to do with the changes in this PR.

**Comment by jc21** [comment]
You might have to rebase on the `develop` branch again as the python build error fix has been added

**Comment by jc21** [comment]
This is an automated message from CI:

Docker Image for build 2 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-1600`

**Note:** ensure you backup your NPM instance before testing this PR image! Especially if this PR contains database changes.

**Comment by jc21** [comment]
This is an automated message from CI:

Docker Image for build 5 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-1600`

**Note:** ensure you backup your NPM instance before testing this PR image! Especially if this PR contains database changes.

**Pull request merged**
