### PR TITLE
Add new details about how to run this image on a Raspberry Pi device.

### PR DESCRIPTION
**Pull request by razvanstoica89**

### CODE REVIEW

**Comment by jc21** [comment]
Docker Image for build 1 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-966`

**Comment by jc21** [comment]
Docker Image for build 2 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-966`

**Comment by jc21** [comment]
Docker Image for build 3 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-966`

**Comment by jc21** [comment]
After thinking about this, I think that people running on a Rpi should probably use Sqlite first. There are numerous issues open for people having trouble getting mysql working on their pi's. Plus sqlite would be less resource heavy. Thoughts?

**Comment by Jiriteach** [comment]
@jc21  - I've been running on an RPI 4(8GB) and have no problems. There was some initial issues with the db build but no issues since then. Clearer instructions around setting it up on an RPI would be valuable. Took me some time to work things out.

**Comment by jc21** [comment]
I only have pi 3's and I often run in to mem issues. I'm just thinking about those who are running homeassistant and other things on it too. Anyway this is a great effort :)

**Pull request merged**
