### PR TITLE
Add support for Infomaniak and IONOS certbot plugins

### PR DESCRIPTION
**Pull request by Fuechslein**

### CODE REVIEW

**Comment by Nobri** [comment]
Would love to see this being implemented, because I am hosting my stuff @IONOS.

**Comment by Fuechslein** [comment]
@jc21 any idea why this fails?

**Comment by jc21** [comment]
This is an automated message from CI:

Docker Image for build 5 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-1149`

**Note:** ensure you backup your NPM instance before testing this PR image! Especially if this PR contains database changes.

**Comment by jc21** [comment]
> @jc21 any idea why this fails?

It was a CI problem, not a patch problem. Now that it's passed, please grab that docker image and test it for those services you've added. thanks :)

**Comment by Fuechslein** [comment]
I tested it for multiple Ionos and Infomanik domains without issues.

**Pull request merged**
