### PR TITLE
#65 custom config of location / on proxy host pane

### LINKED ISSUE #65: Allow full nginx config editing
do you think we can have full access to to config file under advanced settings so we can edit as we like please

### PR DESCRIPTION
**Pull request by kolbii**
Fixes #65 
Adds a new field to Proxy host and puts the generator that code into the root location block's body.
[screenshot](https://imgur.com/a/eTIos3M)

### CODE REVIEW

**Comment by jc21** [comment]
Docker Image for build 4 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-75`

**Comment by kolbii** [comment]
Is this tag`jc21/nginx-proxy-manager:github-pr-75` available on DockerHub? Trying to get this image down but it looks like still unpublished

**Comment by jc21** [comment]
Docker Image for build 5 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-75`

**Comment by jc21** [comment]
Hmm yeah it said it uploaded it but I can't see it either.

**Comment by jc21** [comment]
Docker Image for build 6 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-75`

**Comment by jc21** [comment]
Thanks for contributing to fix this problem. I've been thinking about it and the problem has a simpler solution. The template render of the host nginx config file just needs to ignore the default location when one is present in the advanced config. I've made a quick prototype and it works well.

I'd like to keep the configuration simple, and by that I mean not confusing for those not educated in nginx internals. By adding a special configuration on top of the advanced configuration page seems a bit much.

I'll push another PR with my idea should you want to compare and comment.

**Comment by kolbii** [comment]
You're right. It's simpler like having another input for overriding any params. I'm closing this PR.
However, what do you think about the custom locations section? I think it'd be easier to manage 2+ simple proxied location blocks like writing advanced config. Please take a look at the other one #74 by me.

**Pull request closed without merging**
